formation_homepage:
    path:     /formation
    defaults: { _controller: FormationBundle:Default:index }

ajouter_etudiant:
    path:     /Etudiant/ajouterEtudiant
    defaults: { _controller: FormationBundle:Etudiant:ajouterEtudiant }

modifier_etudiant:
    path:     /Etudiant/modiferEtudiant/{id}
    defaults: { _controller: FormationBundle:Etudiant:modifierEtudiant }
    requirements:
            id: \d+

supprimer_etudiant:
    path:     /Etudiant/supprimerEtudiant/{id}
    defaults: { _controller: FormationBundle:Etudiant:supprimerEtudiant }
    requirements:
            id: \d+

afficher_etudiant:
    path:     /Etudiant/
    defaults: { _controller: FormationBundle:Etudiant:afficherEtudiant }

affecter_etudiant:
    path:     /Etudiant/affecterEtudiant/{id}
    defaults: { _controller: FormationBundle:Etudiant:affecterEtudiant }
    requirements:
            id: \d+
